"""fixtures

Revision ID: 170c0d524b7a
Revises: d7ad306c967a
Create Date: 2021-11-27 16:31:17.263689

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = '170c0d524b7a'
down_revision = 'd7ad306c967a'
branch_labels = None
depends_on = None


def upgrade():
    statements = (
        """INSERT INTO "genre" (name) VALUES ('Electronic');""",
        """INSERT INTO "genre" (name) VALUES ('Rock');""",
        """INSERT INTO "genre" (name) VALUES ('Jazz');""",
        """INSERT INTO "genre" (name) VALUES ('Hip-Hop');""",
        """INSERT INTO "genre" (name) VALUES ('Ambient');""",
        """INSERT INTO "genre" (name) VALUES ('Drum & Bass');""",
        """INSERT INTO "genre" (name) VALUES ('Techno');""",
        """INSERT INTO "genre" (name) VALUES ('Dubstep');""",
        """INSERT INTO "genre" (name) VALUES ('Grime');""",
        """INSERT INTO "genre" (name) VALUES ('Avantgarde');""",
        """INSERT INTO "genre" (name) VALUES ('Indietronic');""",
        """INSERT INTO "genre" (name) VALUES ('Surf Rock');""",
        """INSERT INTO "genre" (name) VALUES ('Kraut Rock');""",
        """INSERT INTO "genre" (name) VALUES ('Post Rock');""",
        """INSERT INTO "genre" (name) VALUES ('Dark Jazz');""",
        """INSERT INTO "genre" (name) VALUES ('Noir Jazz');""",
        """INSERT INTO "genre" (name) VALUES ('Abstract Hip-Hop');""",
        """INSERT INTO "genre" (name) VALUES ('Instrumental Hip-Hop');""",
        """INSERT INTO "genre" (name) VALUES ('Folk Ambient');""",
        """INSERT INTO "genre" (name) VALUES ('Drone Ambient');""",
        """INSERT INTO "genre" (name) VALUES ('Tech Step');""",
        """INSERT INTO "genre" (name) VALUES ('Half Time');""",
        """INSERT INTO "genre" (name) VALUES ('Liquid Drum & Bass');""",
        """INSERT INTO "genre" (name) VALUES ('Garage');""",
        """INSERT INTO "genre" (name) VALUES ('Future Garage');""",
        """INSERT INTO "genre" (name) VALUES ('2 Step');""",
        """INSERT INTO "genre" (name) VALUES ('Deep Dubstep');""",
        """INSERT INTO "genre" (name) VALUES ('Electro');""",
        """INSERT INTO "genre" (name) VALUES ('House');""",

        """INSERT INTO "record_label" (name) VALUES ('VCO Records');""",
        """INSERT INTO "record_label" (name) VALUES ('Pye Corner Audio');""",
        """INSERT INTO "record_label" (name) VALUES ('Metalheadz');""",
        """INSERT INTO "record_label" (name) VALUES ('Восход');""",
        """INSERT INTO "record_label" (name) VALUES ('Instant Classic');""",
        """INSERT INTO "record_label" (name) VALUES ('U Know Me');""",
        """INSERT INTO "record_label" (name) VALUES ('Invada');""",
        """INSERT INTO "record_label" (name) VALUES ('Hospital Records');""",
        """INSERT INTO "record_label" (name) VALUES ('Photek Productions');""",
        """INSERT INTO "record_label" (name) VALUES ('Kompakt');""",
        
        """INSERT INTO "artist" (name) VALUES ('London Electricity');""",
        """INSERT INTO "artist" (name) VALUES ('Рубль');""",
        """INSERT INTO "artist" (name) VALUES ('Head Technician');""",
        """INSERT INTO "artist" (name) VALUES ('Abul Mogard');""",
        """INSERT INTO "artist" (name) VALUES ('Lotto');""",
        """INSERT INTO "artist" (name) VALUES ('TVB');""",
        """INSERT INTO "artist" (name) VALUES ('Beak>');""",
        """INSERT INTO "artist" (name) VALUES ('Friske');""",
        """INSERT INTO "artist" (name) VALUES ('Photek');""",
        """INSERT INTO "artist" (name) VALUES ('Gus Gus');""",

        """INSERT INTO "tag" (name) VALUES ('experimental');""",
        """INSERT INTO "tag" (name) VALUES ('live');""",
        """INSERT INTO "tag" (name) VALUES ('modular');""",
        """INSERT INTO "tag" (name) VALUES ('analog');""",
        """INSERT INTO "tag" (name) VALUES ('percussion');""",
        """INSERT INTO "tag" (name) VALUES ('drums');""",
        """INSERT INTO "tag" (name) VALUES ('stomp');""",
        """INSERT INTO "tag" (name) VALUES ('step');""",
        """INSERT INTO "tag" (name) VALUES ('bleep');""",
        """INSERT INTO "tag" (name) VALUES ('instrumental');""",

        """INSERT INTO "release" (name, artist_id, record_label_id, year) VALUES ('Billion Dollar Gravy', 1, 3, 2003);""",
        """INSERT INTO "release" (name, artist_id, record_label_id, year) VALUES ('Сдачи не надо', 2, 4, 2010);""",
        """INSERT INTO "release" (name, artist_id, record_label_id, year) VALUES ('Profane Architecture', 3, 2, 2018);""",
        """INSERT INTO "release" (name, artist_id, record_label_id, year) VALUES ('Drifted Heaven', 4, 1, 2014);""",
        """INSERT INTO "release" (name, artist_id, record_label_id, year) VALUES ('Elite Feline', 5, 5, 2016);""",
        """INSERT INTO "release" (name, artist_id, record_label_id, year) VALUES ('Agrest', 6, 6, 2021);""",
        """INSERT INTO "release" (name, artist_id, record_label_id, year) VALUES ('>>>', 7, 7, 2018);""",
        """INSERT INTO "release" (name, artist_id, record_label_id, year) VALUES ('A Different Perspective', 8, 3, 2020);""",
        """INSERT INTO "release" (name, artist_id, record_label_id, year) VALUES ('Something Else... The Bleeps Tune', 9, 9, 1999);""",
        """INSERT INTO "release" (name, artist_id, record_label_id, year) VALUES ('Arabian Horse', 10, 10, 2011);""",

        """INSERT INTO "track" (name, release_id) VALUES ('The Great Drum+Bass Swindle', 1);""",
        """INSERT INTO "track" (name, release_id) VALUES ('Fast Soul Music', 1);""",
        """INSERT INTO "track" (name, release_id) VALUES ('Different Drum', 1);""",
        """INSERT INTO "track" (name, release_id) VALUES ('Syncopated City', 1);""",
        """INSERT INTO "track" (name, release_id) VALUES ('To Be Me', 1);""",
        """INSERT INTO "track" (name, release_id) VALUES ('Cum Dancing (V.I.P. Mix)', 1);""",
        """INSERT INTO "track" (name, release_id) VALUES ('Олимпиада', 2);""",
        """INSERT INTO "track" (name, release_id) VALUES ('В Мире Животных', 2);""",
        """INSERT INTO "track" (name, release_id) VALUES ('Я, Гитара И Костюм', 2);""",
        """INSERT INTO "track" (name, release_id) VALUES ('Терпи', 2);""",
        """INSERT INTO "track" (name, release_id) VALUES ('Русский Рок', 2);""",
        """INSERT INTO "track" (name, release_id) VALUES ('50', 2);""",
        """INSERT INTO "track" (name, release_id) VALUES ('Любовь - Это...', 2);""",
        """INSERT INTO "track" (name, release_id) VALUES ('Без Разницы', 2);""",
        """INSERT INTO "track" (name, release_id) VALUES ('Праздник', 2);""",
        """INSERT INTO "track" (name, release_id) VALUES ('Доширак', 2);""",
        """INSERT INTO "track" (name, release_id) VALUES ('Выходной', 2);""",
        """INSERT INTO "track" (name, release_id) VALUES ('Рождество', 2);""",
        """INSERT INTO "track" (name, release_id) VALUES ('Легенды Говнорока', 2);""",
        """INSERT INTO "track" (name, release_id) VALUES ('Время Водка', 2);""",
        """INSERT INTO "track" (name, release_id) VALUES ('Ничего Нового', 2);""",
        """INSERT INTO "track" (name, release_id) VALUES ('Сдача', 2);""",
        """INSERT INTO "track" (name, release_id) VALUES ('Мы Играли', 2);""",
        """INSERT INTO "track" (name, release_id) VALUES ('Любовь', 2);""",
        """INSERT INTO "track" (name, release_id) VALUES ('First Pour', 3);""",
        """INSERT INTO "track" (name, release_id) VALUES ('Béton Brut', 3);""",
        """INSERT INTO "track" (name, release_id) VALUES ('Formwork', 3);""",
        """INSERT INTO "track" (name, release_id) VALUES ('Habitation', 3);""",
        """INSERT INTO "track" (name, release_id) VALUES ('Second Pour', 3);""",
        """INSERT INTO "track" (name, release_id) VALUES ('The New Brutalism', 3);""",
        """INSERT INTO "track" (name, release_id) VALUES ('Decay Blossoms', 3);""",
        """INSERT INTO "track" (name, release_id) VALUES ('Demolition', 3);""",
        """INSERT INTO "track" (name, release_id) VALUES ('Post-Crisis Remembrance', 4);""",
        """INSERT INTO "track" (name, release_id) VALUES ('Tumbling Relentless Heaps', 4);""",
        """INSERT INTO "track" (name, release_id) VALUES ('The Other Room', 4);""",
        """INSERT INTO "track" (name, release_id) VALUES ('Unarmoured Love', 4);""",
        """INSERT INTO "track" (name, release_id) VALUES ('Airless Linger', 4);""",
        """INSERT INTO "track" (name, release_id) VALUES ('Drifted Haven', 4);""",
        """INSERT INTO "track" (name, release_id) VALUES ('Rope', 5);""",
        """INSERT INTO "track" (name, release_id) VALUES ('Pointing To A Marvel', 5);""",
        """INSERT INTO "track" (name, release_id) VALUES ('Going Crazy', 6);""",
        """INSERT INTO "track" (name, release_id) VALUES ('Concentrate', 6);""",
        """INSERT INTO "track" (name, release_id) VALUES ('Na Niby feat. Ania Dudek', 6);""",
        """INSERT INTO "track" (name, release_id) VALUES ('Agrest', 6);""",
        """INSERT INTO "track" (name, release_id) VALUES ('Naughty Selecta', 6);""",
        """INSERT INTO "track" (name, release_id) VALUES ('The Brazilian', 7);""",
        """INSERT INTO "track" (name, release_id) VALUES ('Brean Down', 7);""",
        """INSERT INTO "track" (name, release_id) VALUES ('Birthday Suit', 7);""",
        """INSERT INTO "track" (name, release_id) VALUES ('Harvester', 7);""",
        """INSERT INTO "track" (name, release_id) VALUES ('Allé Sauvage', 7);""",
        """INSERT INTO "track" (name, release_id) VALUES ('Teisco', 7);""",
        """INSERT INTO "track" (name, release_id) VALUES ('King Of The Castle', 7);""",
        """INSERT INTO "track" (name, release_id) VALUES ('RSI', 7);""",
        """INSERT INTO "track" (name, release_id) VALUES ('Abbots Leigh', 7);""",
        """INSERT INTO "track" (name, release_id) VALUES ('When We Fall', 7);""",
        """INSERT INTO "track" (name, release_id) VALUES ('A Different Perspective', 8);""",
        """INSERT INTO "track" (name, release_id) VALUES ('Destination', 8);""",
        """INSERT INTO "track" (name, release_id) VALUES ('Introspect', 8);""",
        """INSERT INTO "track" (name, release_id) VALUES ('Untitled Piano', 8);""",
        """INSERT INTO "track" (name, release_id) VALUES ('Starship', 8);""",
        """INSERT INTO "track" (name, release_id) VALUES ('The Love We Had', 8);""",
        """INSERT INTO "track" (name, release_id) VALUES ('Skyline', 8);""",
        """INSERT INTO "track" (name, release_id) VALUES ('Purple Sky', 8);""",
        """INSERT INTO "track" (name, release_id) VALUES ('Beacon', 8);""",
        """INSERT INTO "track" (name, release_id) VALUES ('Urban Decay', 8);""",
        """INSERT INTO "track" (name, release_id) VALUES ('Sabotage', 8);""",
        """INSERT INTO "track" (name, release_id) VALUES ('Control Remix', 8);""",
        """INSERT INTO "track" (name, release_id) VALUES ('Crime In The City', 8);""",
        """INSERT INTO "track" (name, release_id) VALUES ('Gangway', 8);""",
        """INSERT INTO "track" (name, release_id) VALUES ('Resistance', 8);""",
        """INSERT INTO "track" (name, release_id) VALUES ('Rebel Force', 8);""",
        """INSERT INTO "track" (name, release_id) VALUES ('Something Else... The Bleeps Tune (Original Version)', 9);""",
        """INSERT INTO "track" (name, release_id) VALUES ('Something Else... The Bleeps Tune (Photek Remix)', 9);""",

        """INSERT INTO "release_tag" (release_id, tag_id) VALUES (1, 2);""",
        """INSERT INTO "release_tag" (release_id, tag_id) VALUES (2, 2);""",
        """INSERT INTO "release_tag" (release_id, tag_id) VALUES (2, 10);""",
        """INSERT INTO "release_tag" (release_id, tag_id) VALUES (3, 4);""",
        """INSERT INTO "release_tag" (release_id, tag_id) VALUES (4, 4);""",
        """INSERT INTO "release_tag" (release_id, tag_id) VALUES (4, 10);""",
        """INSERT INTO "release_tag" (release_id, tag_id) VALUES (5, 5);""",
        """INSERT INTO "release_tag" (release_id, tag_id) VALUES (5, 6);""",
        """INSERT INTO "release_tag" (release_id, tag_id) VALUES (5, 10);""",
        """INSERT INTO "release_tag" (release_id, tag_id) VALUES (6, 1);""",
        """INSERT INTO "release_tag" (release_id, tag_id) VALUES (6, 8);""",
        """INSERT INTO "release_tag" (release_id, tag_id) VALUES (7, 1);""",
        """INSERT INTO "release_tag" (release_id, tag_id) VALUES (7, 6);""",
        """INSERT INTO "release_tag" (release_id, tag_id) VALUES (8, 7);""",
        """INSERT INTO "release_tag" (release_id, tag_id) VALUES (8, 8);""",
        """INSERT INTO "release_tag" (release_id, tag_id) VALUES (9, 5);""",
        """INSERT INTO "release_tag" (release_id, tag_id) VALUES (9, 1);""",
        """INSERT INTO "release_tag" (release_id, tag_id) VALUES (9, 8);""",
        """INSERT INTO "release_tag" (release_id, tag_id) VALUES (9, 9);""",
        """INSERT INTO "release_tag" (release_id, tag_id) VALUES (10, 3);""",
        """INSERT INTO "release_tag" (release_id, tag_id) VALUES (10, 4);""",

        """INSERT INTO "release_genre" (release_id, genre_id) VALUES (1, 1);""",
        """INSERT INTO "release_genre" (release_id, genre_id) VALUES (1, 6);""",
        """INSERT INTO "release_genre" (release_id, genre_id) VALUES (1, 23);""",
        """INSERT INTO "release_genre" (release_id, genre_id) VALUES (2, 12);""",
        """INSERT INTO "release_genre" (release_id, genre_id) VALUES (2, 2);""",
        """INSERT INTO "release_genre" (release_id, genre_id) VALUES (3, 1);""",
        """INSERT INTO "release_genre" (release_id, genre_id) VALUES (3, 7);""",
        """INSERT INTO "release_genre" (release_id, genre_id) VALUES (4, 1);""",
        """INSERT INTO "release_genre" (release_id, genre_id) VALUES (4, 5);""",
        """INSERT INTO "release_genre" (release_id, genre_id) VALUES (4, 20);""",
        """INSERT INTO "release_genre" (release_id, genre_id) VALUES (5, 2);""",
        """INSERT INTO "release_genre" (release_id, genre_id) VALUES (5, 10);""",
        """INSERT INTO "release_genre" (release_id, genre_id) VALUES (5, 13);""",
        """INSERT INTO "release_genre" (release_id, genre_id) VALUES (5, 14);""",
        """INSERT INTO "release_genre" (release_id, genre_id) VALUES (6, 6);""",
        """INSERT INTO "release_genre" (release_id, genre_id) VALUES (6, 24);""",
        """INSERT INTO "release_genre" (release_id, genre_id) VALUES (6, 26);""",
        """INSERT INTO "release_genre" (release_id, genre_id) VALUES (7, 2);""",
        """INSERT INTO "release_genre" (release_id, genre_id) VALUES (7, 13);""",
        """INSERT INTO "release_genre" (release_id, genre_id) VALUES (7, 14);""",
        """INSERT INTO "release_genre" (release_id, genre_id) VALUES (7, 10);""",
        """INSERT INTO "release_genre" (release_id, genre_id) VALUES (8, 6);""",
        """INSERT INTO "release_genre" (release_id, genre_id) VALUES (8, 21);""",
        """INSERT INTO "release_genre" (release_id, genre_id) VALUES (9, 6);""",
        """INSERT INTO "release_genre" (release_id, genre_id) VALUES (9, 21);""",
        """INSERT INTO "release_genre" (release_id, genre_id) VALUES (10, 7);""",
        """INSERT INTO "release_genre" (release_id, genre_id) VALUES (10, 29);""",
        """INSERT INTO "release_genre" (release_id, genre_id) VALUES (10, 1);""",

        """INSERT INTO "mood" (name) VALUES ('Running');""",
        """INSERT INTO "mood" (name) VALUES ('Cycling');""",
        """INSERT INTO "mood" (name) VALUES ('Home listening');""",
        """INSERT INTO "mood" (name) VALUES ('Working');""",
        """INSERT INTO "mood" (name) VALUES ('Chilling');""",
        """INSERT INTO "mood" (name) VALUES ('Relaxation');""",
        """INSERT INTO "mood" (name) VALUES ('Sad');""",
        """INSERT INTO "mood" (name) VALUES ('Energetic');""",

        """INSERT INTO "playlist" (name, mood_id, record_label_id, artist_id) VALUES ('Rock', NULL, NULL, NULL);""",
        """INSERT INTO "playlist" (name, mood_id, record_label_id, artist_id) VALUES ('D`n`B', NULL, NULL, NULL);""",
        """INSERT INTO "playlist" (name, mood_id, record_label_id, artist_id) VALUES ('Techy stompy choonz', NULL, NULL, NULL);""",
        """INSERT INTO "playlist" (name, mood_id, record_label_id, artist_id) VALUES ('Synth electronic', NULL, NULL, NULL);""",

        """INSERT INTO "playlist_genre" (playlist_id, genre_id) VALUES (3, 21);""",
        """INSERT INTO "playlist_genre" (playlist_id, genre_id) VALUES (4, 1);""",
        """INSERT INTO "playlist_genre" (playlist_id, genre_id) VALUES (4, 5);""",

        """INSERT INTO "playlist_tag" (playlist_id, tag_id) VALUES (3, 7);""",
        """INSERT INTO "playlist_tag" (playlist_id, tag_id) VALUES (4, 1);""",
        """INSERT INTO "playlist_tag" (playlist_id, tag_id) VALUES (4, 3);""",
        """INSERT INTO "playlist_tag" (playlist_id, tag_id) VALUES (4, 4);""",
    )

    for statement in statements:
        op.execute(statement)


def downgrade():
    statements = (
        'TRUNCATE TABLE "playlist_tag" RESTART IDENTITY CASCADE;',
        'TRUNCATE TABLE "playlist_genre" RESTART IDENTITY CASCADE;',
        'TRUNCATE TABLE "playlist" RESTART IDENTITY CASCADE;',
        'TRUNCATE TABLE "playlist_track" RESTART IDENTITY CASCADE;',
        'TRUNCATE TABLE "playlist" RESTART IDENTITY CASCADE;',
        'TRUNCATE TABLE "mood" RESTART IDENTITY CASCADE;',
        'TRUNCATE TABLE "track" RESTART IDENTITY CASCADE;',
        'TRUNCATE TABLE "release_genre" RESTART IDENTITY CASCADE;',
        'TRUNCATE TABLE "release_tag" RESTART IDENTITY CASCADE;',
        'TRUNCATE TABLE "release" RESTART IDENTITY CASCADE;',
        'TRUNCATE TABLE "artist" RESTART IDENTITY CASCADE;',
        'TRUNCATE TABLE "tag" RESTART IDENTITY CASCADE;',
        'TRUNCATE TABLE "record_label" RESTART IDENTITY CASCADE;',
        'TRUNCATE TABLE "genre" RESTART IDENTITY CASCADE;',
    )

    for statement in statements:
        op.execute(statement)
